### ISSUE TITLE
Sentry not reporting subsequent events

### ISSUE THREAD

**Issue by dwickwire** [getsentry/perl-raven#25]
Hello,

We're having a problem where subsequent events of an exception aren't being reported to sentry.

Basically we created a test file, cause an error it reports to sentry normally.  Then we rerun but there's only one recorded event of the exception.

We're using VERSION: 1.10 with Sentry 8.20.0.

#### test.pl
```perl
use Sentry::Raven;
use strict;
use warnings;

sub sentry {
    return Sentry::Raven->new(sentry_dsn => <our-dsn>);
}

1;
```

We saw this error before in a python backend once, is this a bug in the Sentry::Raven perl module?

**Comment by querry43** [comment]
I have definitely been confused by this before but I don't think it's a client problem.  Sentry on the server-side threads similar items together and it is my experience that you might not be able to see all occurrences in a thread.  I'm not certain if this is part of the sampling they do or a bug.

If you want the two events to be more visible, try setting fingerprint to a unique value (like the time) for both events to keep them from threading.  If that doesn't help, I recommend asking sentry support for help tracking down both discrete events.  They are always super responsive.
