### ISSUE TITLE
Need update for new DSN format

### ISSUE THREAD

**Issue by robn** [getsentry/perl-raven#26]
https://docs.sentry.io/quickstart/#configure-the-dsn

Secret key is no longer included in the DSN.

**Comment by querry43** [comment]
@robn , I am looking at the documentation and it looks like there is a public option for javascript which runs on browsers where the dsn is readable, but there is still a private option for server-side code.  For a perl client, it probably makes sense to continue using the non-public DSN.  I have confirmed this still works.

However, while I was in here, I did update the DSN templates in the documentation to a more current format (https, sentry.io).

**Comment by gugod** [comment]
@robn, @querry43 

https://docs.sentry.io/development/sdk-dev/overview/#parsing-the-dsn

FYI, in a different piece of documentation, it is stated that the secret is is ignored by Sentry:

> Note
> 
> The secret part of the DSN is optional and effectively deprecated at this point. While clients are still supposed to honor it if supplied future versions of Sentry will entirely ignore it. The DSN parsing code must not require the secret key to be set.
