### ISSUE TITLE
Display source code directly in Sentry?

### ISSUE THREAD

**Issue by Nowaker** [getsentry/perl-raven#28]
It'd be nice if Sentry::Raven could also gather partial source code around each line of the stacktrace. This is how it looks out of the box for Python events:

![image](https://user-images.githubusercontent.com/611746/73099297-d2cc6c00-3eb0-11ea-81c3-5a635592e29a.png)

**Comment by Nowaker** [comment]
I've been looking through the SDK docs and found this: https://docs.sentry.io/development/sdk-dev/event-payloads/stacktrace/

- context_line: Source code in filename at `lineno`.
- pre_context: A list of source code lines before `context_line` (in order) – usually `[lineno - 5:lineno]`.
- post_context: A list of source code lines after `context_line` (in order) – usually `[lineno + 1:lineno + 5]`.

Here's how it's implemented in Python SDK: https://github.com/getsentry/sentry-python/blob/8ed8f4548a32208890de7515f6ec0672ac147692/sentry_sdk/utils.py#L276 - we would need something similar in Sentry::Raven.

```python
def get_lines_from_file(
    filename,  # type: str
    lineno,  # type: int
    loader=None,  # type: Optional[Any]
    module=None,  # type: Optional[str]
):
    # type: (...) -> Tuple[List[Annotated[str]], Optional[Annotated[str]], List[Annotated[str]]]
    context_lines = 5
    source = None
    if loader is not None and hasattr(loader, "get_source"):
        try:
            source_str = loader.get_source(module)  # type: Optional[str]
        except (ImportError, IOError):
            source_str = None
        if source_str is not None:
            source = source_str.splitlines()

    if source is None:
        try:
            source = linecache.getlines(filename)
        except (OSError, IOError):
            return [], None, []

    if not source:
        return [], None, []

    lower_bound = max(0, lineno - context_lines)
    upper_bound = min(lineno + 1 + context_lines, len(source))

    try:
        pre_context = [
            strip_string(line.strip("\r\n")) for line in source[lower_bound:lineno]
        ]
        context_line = strip_string(source[lineno].strip("\r\n"))
        post_context = [
            strip_string(line.strip("\r\n"))
            for line in source[(lineno + 1) : upper_bound]
        ]
        return pre_context, context_line, post_context
    except IndexError:
        # the file may have changed since it was loaded into memory
        return [], None, []
```

**Comment by Nowaker** [comment]
We'd need code similar to Python code above around this location in our SDK: https://github.com/getsentry/perl-raven/blob/6f6429335fcc75ef899975c3fb763d67ad08c957/lib/Sentry/Raven.pm#L284

**Comment by mbudde** [comment]
We have added this in our Mojolicious application by manually inserting the source code context from [Mojo::Exception](https://mojolicious.org/perldoc/Mojo/Exception) into the output from Sentry::Raven->stacktrace_context. Something like this:
```perl
# $exc: Mojo::Exception
my $stacktrace = $exc->stacktrace;
my %context = Sentry::Raven->stacktrace_context($stacktrace);
my $frame = $context{'sentry.interfaces.Stacktrace'}->{frames}->[-1];
$frame->{context_line} = $exc->line->[1];
$frame->{pre_context}  = [ map { $_->[1] } $exc->lines_before->@* ];
$frame->{post_context} = [ map { $_->[1] } $exc->lines_after->@* ];
```

**Comment by xca** [comment]
regarding this pr, #32  is confirmed working and should address it.
