### ISSUE TITLE
SDK Docs

### ISSUE THREAD

**Issue by dcramer** [getsentry/perl-raven#6]
I put up some informal docs for the Perl client on our new docs.getsentry.com site:

https://docs.getsentry.com/hosted/clients/perl/

We'd love to move this into the repo to support some various behaviors. If that sounds good, there's a couple of approaches we'd prefer to take:
1. Add a few of us as collaborators here
2. Let us move the repo to the getsentry org space (we'll retain the current permissions)

It's unlikely we'll be able to help maintain the SDK itself (as none of us use Perl), but we can help out with some of the community/documentation things.

**Comment by dcramer** [comment]
Also FWIW we can keep this in the sentry-docs repo, so dont consider this a requirement.

**Comment by querry43** [comment]
I think for the code to stay alive and active, this is the right direction,
but I am not sure how best to manage the documentation.  It is embedded
right now in the code which is good for two reasons:

1. man and perldoc work
2. it is super convenient when modifying the code to have documentation on
hand

Is the proposal here to split the documentation out to somewhere it might
be better maintained but no longer accessible to man and perldoc?

**Comment by dcramer** [comment]
It would likely duplicate some of the documentation:

https://github.com/getsentry/sentry-docs/blob/master/docs/clients/perl/index.rst

Right now we're pushing the page into sentry-docs, but for a lot of the other SDKs we actually just pull them in as submodules.

I dont think we'd have to put a ton of effort into adding more content, it's mostly around discovery of the project and some basic getting started docs. We can continue just to refer to CPAN and things for full API documentation. Our main goal with the docs is primarily for a "heres how to get started" or "heres how to integrate with X framework".

**Comment by querry43** [comment]
Ok, I can't quite figure out how to get you added.  Can you request to be a
member of rentrak?

https://github.com/orgs/rentrak/people

**Comment by dcramer** [comment]
Looks like I have access now.  We'll move the docs over so they get versioned with the code (and are a bit more accessible). Will send a PR so you have an idea of how things look.

**Comment by querry43** [comment]
I like your idea to move the whole package into the getsentry org. We all
agreed that was the best way to keep the code relevant and up to date. If
you want, go ahead and do that. I may need to change some build metadata
afterwards.

**Comment by dcramer** [comment]
@querry43 I sent you an invite to the Perl team on getsentry. This has changed a little bit, but I believe you can transfer the repo once you've accepted the invite. I can also add anyone else there that's still active on the project.

**Comment by querry43** [comment]
It would seem I need admin rights to getsentry to make the move.  You now
have admin rights on rentrak/perl-raven.  Do you want to try doing the move
again?

**Comment by dcramer** [comment]
All set!

**Comment by querry43** [comment]
Great, thanks.  I've got a pull request that I can use to test perms and
whatnot.  I guess no one else at rentrak has made direct changes in this
repo so we don't need any more privs yet.

**Comment by querry43** [comment]
David, seems I don't have write permission on the new repo.  Mind throwing
that my way so I can update metadata and handle this pending pr?

**Comment by dcramer** [comment]
@querry43 I think its fixed now. Still getting used to the role changes on GH.

**Comment by querry43** [comment]
Works for me!
